# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Judge0Uploader < Formula
  desc "Judge0 utility to upload files and test them directly from the terminal"
  homepage "https://github.com/roeeyn/homebrew-tools"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roeeyn/judge0-uploader/releases/download/v0.0.1/judge0-uploader_0.0.1_darwin_amd64.tar.gz"
      sha256 "92997db5258f2425c0b2d884d33d5f46f7c94ee8361a1d8a9bb227bd1453e9be"

      def install
        bin.install "judge0-uploader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roeeyn/judge0-uploader/releases/download/v0.0.1/judge0-uploader_0.0.1_darwin_arm64.tar.gz"
      sha256 "d159f1dfc852217e6c7c64740590e5ae52a11c27895176c89a798b6ed895a674"

      def install
        bin.install "judge0-uploader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/roeeyn/judge0-uploader/releases/download/v0.0.1/judge0-uploader_0.0.1_linux_amd64.tar.gz"
      sha256 "042de3088a305c1bdaf9363493c1e5e4e9a0c16f9680b6abc25b6ba8b89727c8"

      def install
        bin.install "judge0-uploader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roeeyn/judge0-uploader/releases/download/v0.0.1/judge0-uploader_0.0.1_linux_arm64.tar.gz"
      sha256 "a63b9cc03dc55e1d857d27318cb245bfafded9224ba59b64679d1520a9d8ec58"

      def install
        bin.install "judge0-uploader"
      end
    end
  end
end
