# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Judge0Uploader < Formula
  desc "Judge0 utility to upload files and test them directly from the terminal"
  homepage "https://github.com/roeeyn/judge0-uploader"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/roeeyn/judge0-uploader/releases/download/v0.0.2/judge0-uploader_0.0.2_darwin_arm64.tar.gz"
      sha256 "a59555edca837a74ac19636eca6418fca78f804b6e4573d1dc81f9ea9fd571e4"

      def install
        bin.install "judge0-uploader"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/roeeyn/judge0-uploader/releases/download/v0.0.2/judge0-uploader_0.0.2_darwin_amd64.tar.gz"
      sha256 "f7aebd1cbf4a662306b15004ff0fbb3add2622c6bf508f51bcb6e53dde3f10ba"

      def install
        bin.install "judge0-uploader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roeeyn/judge0-uploader/releases/download/v0.0.2/judge0-uploader_0.0.2_linux_arm64.tar.gz"
      sha256 "b83269b848da825503280698fc4bd1739e4cfec89e73363083b2c38ee5492dbf"

      def install
        bin.install "judge0-uploader"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/roeeyn/judge0-uploader/releases/download/v0.0.2/judge0-uploader_0.0.2_linux_amd64.tar.gz"
      sha256 "77cfbafe28a851f0da21dbfa9a02b12134aec34482f0bbdc0443ecc8db57e23e"

      def install
        bin.install "judge0-uploader"
      end
    end
  end
end
