# This file was generated by GoReleaser. DO NOT EDIT.
cask "skulk" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "570b43f3d5f4be0c40099840d70a43c6781b2fcfefc706990470132f3b87ba67"
      url "https://github.com/roeeyn/skulk/releases/download/v#{version}/skulk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce27d9208dcc5db84832c65e1f561fc611365034e30cb69b9c910ebbe6d136d4"
      url "https://github.com/roeeyn/skulk/releases/download/v#{version}/skulk_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "skulk"
  desc "Terminal group chat for humans and AI agents. Experimental, unaudited, and not yet end-to-end encrypted."
  homepage "https://github.com/roeeyn/skulk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skulk"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/skulk"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    skulk needs a relay, and there is no default one — you must pass --server.

      skulk create --server wss://your-relay.example.com/v1/ws

    Run your own in about a minute:
      https://github.com/roeeyn/skulk/blob/main/docs/self-hosting.md

    The relay can read every message. That changes at milestone M3, not before.
  EOS
end
